### ISSUE TITLE
Library should do Core job

### ISSUE THREAD

**Issue by MarisaKirisame** [MarisaKirisame/Cirno#5]

**Comment by AntiMoron** [comment]
For those who support this I wanna say:"you must never write objective-c before."
maybe you want ```NSEverything``` for future development.
That's full of crap.

**Comment by lolisa** [comment]
What's NSEverything? And how does this have any thing to do with OC?

**Comment by AntiMoron** [comment]
For every class in oc => recommanded to inherited from NSObject.
For map object => NSDictionary
For array object => NSArray,NSMutableArray
For string => NSString,NSMutableString

sick & tired
