### ISSUE TITLE
null pointers are harmful.Do never add it.

### ISSUE THREAD

**Issue by AntiMoron** [MarisaKirisame/Cirno#9]

**Comment by lolisa** [comment]
How else are you gonna represent something that may not have value?

**Comment by AntiMoron** [comment]
Don't make the case happen at all.

Object pointer which points to null always means this object is useless.
Useless things based on useless code is totally useless.
For those failed during their initialization just throw exceptions or terminate.
e.g.
swift: 
```swift
 var p! = NSObject(); 
 var p? = null; 
```

**Comment by AntiMoron** [comment]
Personally I think getting rid of null pointers can reduce bugs of a program for no needs for null pointer checking.

**Comment by AntiMoron** [comment]
For exception ,just upwind them to several places to handle. It's easy.

**Comment by lolisa** [comment]
You seemingly does not understand the spirit of Cirno.
